### ISSUE TITLE
Build failure with Python 3.10

### ISSUE THREAD

**Issue by fabaff** [Julius2342/pyvlx#61]
If running with Python 3.10 then the tests don't pass.

```bash
[...]
self.name)
                        )
E               AttributeError: Command: no attribute
'GW_LEAVE_LEARN_STATE_REQ'

/usr/lib64/python3.10/enum.py:146: AttributeError
=========================== short test summary info
============================
FAILED
test/frame_leave_learn_state_req_test.py::TestFrameLeaveLearnStateRequest::test_frame_from_raw
======================== 1 failed, 287 passed in 0.84s
=========================
```

See https://bugzilla.redhat.com/show_bug.cgi?id=1928062 for details.

Tanks

**Comment by Julius2342** [comment]
3.10 ... cutting edge :)

**Comment by tirkarthi** [comment]
This could be probably due to https://bugs.python.org/issue43162 . Looking at the file everything seems to access from enum while this if clause alone retrieves from the object. I guess it's probably a typo of capital C and lowercase C.

https://github.com/Julius2342/pyvlx/blob/2c19f35ca2f5cb9d318a0e11b8726e388738f8d6/pyvlx/api/frame_creation.py#L180
